// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBusUbYzULrBZTkhUI_DAsk6XihHMNSLOk',
    appId: '1:26333180974:web:de2596ae61e5856f1d9bbf',
    messagingSenderId: '26333180974',
    projectId: 'ghumify-52e7b',
    authDomain: 'ghumify-52e7b.firebaseapp.com',
    storageBucket: 'ghumify-52e7b.firebasestorage.app',
    measurementId: 'G-3PRRRPGFGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMTVFc17YQaXmWLm0aMkp_woou-u5m_w',
    appId: '1:26333180974:android:a3fbe5825272705b1d9bbf',
    messagingSenderId: '26333180974',
    projectId: 'ghumify-52e7b',
    storageBucket: 'ghumify-52e7b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC3kkgGIUjZ1oGI6qGmG7G5jwwAZMcsto',
    appId: '1:26333180974:ios:d8971536cd7a60331d9bbf',
    messagingSenderId: '26333180974',
    projectId: 'ghumify-52e7b',
    storageBucket: 'ghumify-52e7b.firebasestorage.app',
    iosBundleId: 'com.example.ghumifyApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC3kkgGIUjZ1oGI6qGmG7G5jwwAZMcsto',
    appId: '1:26333180974:ios:d8971536cd7a60331d9bbf',
    messagingSenderId: '26333180974',
    projectId: 'ghumify-52e7b',
    storageBucket: 'ghumify-52e7b.firebasestorage.app',
    iosBundleId: 'com.example.ghumifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBusUbYzULrBZTkhUI_DAsk6XihHMNSLOk',
    appId: '1:26333180974:web:fecf52170a88ab4c1d9bbf',
    messagingSenderId: '26333180974',
    projectId: 'ghumify-52e7b',
    authDomain: 'ghumify-52e7b.firebaseapp.com',
    storageBucket: 'ghumify-52e7b.firebasestorage.app',
    measurementId: 'G-1E1NZ7FYV7',
  );
}
