import { TranslationPhrase, LangCode } from './types';

// Common travel phrases with translations in 10 Indian languages.
// The Tourist Translator lets a traveller speak their language and show the
// local-language translation to communicate.

export const TRANSLATOR_CATEGORIES = [
  'Greetings',
  'Food & Restaurant',
  'Shopping & Market',
  'Transport',
  'Hotel',
  'Emergency',
  'Directions',
];

export const PHRASES: TranslationPhrase[] = [
  // ── Greetings ──
  {
    id: 'g-hello',
    category: 'Greetings',
    english: 'Hello / Namaste',
    translations: {
      en: 'Hello',
      hi: 'नमस्ते',
      gu: 'નમસ્તે',
      mr: 'नमस्कार',
      bn: 'নমস্কার',
      ta: 'வணக்கம்',
      te: 'నమస్కారం',
      kn: 'ನಮಸ್ಕಾರ',
      ml: 'നമസ്കാരം',
      pa: 'ਨਮਸਤੇ',
    },
  },
  {
    id: 'g-good-morning',
    category: 'Greetings',
    english: 'Good morning',
    translations: {
      en: 'Good morning',
      hi: 'सुप्रभात',
      gu: 'સુપ્રભાત',
      mr: 'शुभ सकाळ',
      bn: 'সুপ্রভাত',
      ta: 'காலை வணக்கம்',
      te: 'శుభోదయం',
      kn: 'ಶುಭೋದಯ',
      ml: 'സുപ്രഭാതം',
      pa: 'ਸ਼ੁਭ ਸਵੇਰ',
    },
  },
  {
    id: 'g-thankyou',
    category: 'Greetings',
    english: 'Thank you',
    translations: {
      en: 'Thank you',
      hi: 'धन्यवाद',
      gu: 'આભાર',
      mr: 'धन्यवाद',
      bn: 'ধন্যবাদ',
      ta: 'நன்றி',
      te: 'ధన్యవాదాలు',
      kn: 'ಧನ್ಯವಾದಗಳು',
      ml: 'നന്ദി',
      pa: 'ਧੰਨਵਾਦ',
    },
  },
  {
    id: 'g-yesno',
    category: 'Greetings',
    english: 'Yes / No',
    translations: {
      en: 'Yes / No',
      hi: 'हाँ / नहीं',
      gu: 'હા / ના',
      mr: 'होय / नाही',
      bn: 'হ্যাঁ / না',
      ta: 'ஆம் / இல்லை',
      te: 'అవును / కాదు',
      kn: 'ಹೌದು / ಇಲ್ಲ',
      ml: 'അതെ / അല്ല',
      pa: 'ਹਾਂ / ਨਹੀਂ',
    },
  },
  {
    id: 'g-please',
    category: 'Greetings',
    english: 'Please',
    translations: {
      en: 'Please',
      hi: 'कृपया',
      gu: 'કૃપયા',
      mr: 'कृपया',
      bn: 'অনুগ্রহ করে',
      ta: 'தயவு செய்து',
      te: 'దయచేసి',
      kn: 'ದಯವಿಟ್ಟು',
      ml: 'ദയവായി',
      pa: 'ਬਿਨਾਂ ਸਿਰਾਂਦੇ',
    },
  },
  {
    id: 'g-howareyou',
    category: 'Greetings',
    english: 'How are you?',
    translations: {
      en: 'How are you?',
      hi: 'आप कैसे हैं?',
      gu: 'તમે કેમ છો?',
      mr: 'तुम्ही कसे आहात?',
      bn: 'আপনি কেমন আছেন?',
      ta: 'நீங்கள் எப்படி இருக்கிறீர்கள்?',
      te: 'మీరు ఎలా ఉన్నారు?',
      kn: 'ನೀವು ಹೇಗಿದ್ದೀರಿ?',
      ml: 'എങ്ങനെയുണ്ട്?',
      pa: 'ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?',
    },
  },

  // ── Food & Restaurant ──
  {
    id: 'f-hungry',
    category: 'Food & Restaurant',
    english: 'I am hungry',
    translations: {
      en: 'I am hungry',
      hi: 'मुझे भूख लगी है',
      gu: 'મને ભૂખ લાગી છે',
      mr: 'मला भूक लागली आहे',
      bn: 'আমার ক্ষুধা পেয়েছে',
      ta: 'எனக்கு பசி இருக்கிறது',
      te: 'నాకు ఆకలి వేస్తుంది',
      kn: 'ನನಗೆ ಹಸಿವು ಆಗಿದೆ',
      ml: 'എനിക്ക് വയ്യുന്നു',
      pa: 'ਮੈਨੂੰ ਭੁੱਖ ਲੱਗੀ ਹੈ',
    },
  },
  {
    id: 'f-veg',
    category: 'Food & Restaurant',
    english: 'Is this vegetarian?',
    translations: {
      en: 'Is this vegetarian?',
      hi: 'क्या यह शाकाहारी है?',
      gu: 'શું આ શાકાહારી છે?',
      mr: 'हे शाकाहारी आहे का?',
      bn: 'এটা কি নিরামিষ?',
      ta: 'இது சைவமா?',
      te: 'ఇది శాఖాహారమా?',
      kn: 'ಇದು ಸಸ್ಯಾಹಾರವೇ?',
      ml: 'ഇത് സസ്യാഹാരമാണോ?',
      pa: 'ਕੀ ਇਹ ਸ਼ਾਕਾਹਾਰੀ ਹੈ?',
    },
  },
  {
    id: 'f-water',
    category: 'Food & Restaurant',
    english: 'Water, please',
    translations: {
      en: 'Water, please',
      hi: 'पानी चाहिए',
      gu: 'પાણી જોઈએ',
      mr: 'पाणी पाहिजे',
      bn: 'জল দিন',
      ta: 'தண்ணீர் வேண்டும்',
      te: 'నీళ్లు కావాలి',
      kn: 'ನೀರು ಬೇಕು',
      ml: 'വെള്ളം വേണം',
      pa: 'ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ',
    },
  },
  {
    id: 'f-bill',
    category: 'Food & Restaurant',
    english: 'The bill, please',
    translations: {
      en: 'The bill, please',
      hi: 'बिल दें दीजिए',
      gu: 'બિલ આપો',
      mr: 'बिल द्या',
      bn: 'বিল দিন',
      ta: 'பில் கொடுங்கள்',
      te: 'బిల్ ఇవ్వండి',
      kn: 'ಬಿಲ್ ಕೊಡಿ',
      ml: 'ബിൽ തരൂ',
      pa: 'ਬਿਲ ਦੇਵੋ',
    },
  },
  {
    id: 'f-delicious',
    category: 'Food & Restaurant',
    english: 'This is delicious!',
    translations: {
      en: 'This is delicious!',
      hi: 'यह बहुत स्वादिष्ट है!',
      gu: 'આ બહુ સ્વાદિષ્ટ છે!',
      mr: 'हे खूप चवहुन आहे!',
      bn: 'এটা খুব সুস্বাদু!',
      ta: 'இது மிகவும் ருசியாக உள்ளது!',
      te: 'ఇది చాలా రుచిగా ఉంది!',
      kn: 'ಇದು ತುಂಬ ರುಚಿಯಾಗಿದೆ!',
      ml: 'ഇത് വളരെ രുചിയാണ്!',
      pa: 'ਇਹ ਬਹੁਤ ਸਵਾਦ ਹੈ!',
    },
  },
  {
    id: 'f-what-dish',
    category: 'Food & Restaurant',
    english: 'What is this dish?',
    translations: {
      en: 'What is this dish?',
      hi: 'यह क्या व्यंजन है?',
      gu: 'આ કઈ વાનગી છે?',
      mr: 'हे काय जेवण आहे?',
      bn: 'এটা কী খাবার?',
      ta: 'இது என்ன உணவு?',
      te: 'ఇది ఏమి వంట?',
      kn: 'ಇದು ಯಾವ ತಿಂಡಿ?',
      ml: 'ഇത് എന്ത് വിഭവമാണ്?',
      pa: 'ਇਹ ਕੀ ਪਕਵਾਨ ਹੈ?',
    },
  },

  // ── Shopping & Market ──
  {
    id: 's-how-much',
    category: 'Shopping & Market',
    english: 'How much does this cost?',
    translations: {
      en: 'How much does this cost?',
      hi: 'इसका दाम क्या है?',
      gu: 'આની કિંમત શું છે?',
      mr: 'याची किंमत किती?',
      bn: 'এটার দাম কত?',
      ta: 'இதன் விலை என்ன?',
      te: 'దీని ధర ఎంత?',
      kn: 'ಇದರ ಬೆಲೆ ಎಷ್ಟು?',
      ml: 'ഇതിന്റെ വില എത്ര?',
      pa: 'ਇਸ ਦੀ ਕੀਮਤ ਕਿੰਨੀ ਹੈ?',
    },
  },
  {
    id: 's-expensive',
    category: 'Shopping & Market',
    english: 'That\'s too expensive',
    translations: {
      en: 'That\'s too expensive',
      hi: 'यह बहुत महँगा है',
      gu: 'આ બહુ મોંઘુ છે',
      mr: 'हे खूप महाग आहे',
      bn: 'এটা বেশি দামি',
      ta: 'இது மிக விலை அதிகம்',
      te: 'ఇది చాలా ఖరీదు',
      kn: 'ಇದು ತುಂಬ ದುಬಾರಿ',
      ml: 'ഇത് വളരെ ചെലവേറിയതാണ്',
      pa: 'ਇਹ ਬਹੁਤ ਮਹਿੰਗਾ ਹੈ',
    },
  },
  {
    id: 's-cheaper',
    category: 'Shopping & Market',
    english: 'Do you have a cheaper one?',
    translations: {
      en: 'Do you have a cheaper one?',
      hi: 'क्या आपके पास सस्ता है?',
      gu: 'તમારી પાસે સસ્તું છે?',
      mr: 'तुमच्याकडे स्वस्त आहे का?',
      bn: 'এর চেয়ে সস্তা কিছু আছে?',
      ta: 'விலை குறைவானது இருக்கிறதா?',
      te: 'తక్కువ ధర ఉన్నదా?',
      kn: 'ಅಗ್ಗದ್ದು ಇದೆಯೇ?',
      ml: 'ഇതിലും വില കുറഞ്ഞത് ഉണ്ടോ?',
      pa: 'ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਸਸਤਾ ਹੈ?',
    },
  },
  {
    id: 's-ill-take',
    category: 'Shopping & Market',
    english: 'I\'ll take this',
    translations: {
      en: 'I\'ll take this',
      hi: 'मुझे यह चाहिए',
      gu: 'મને આ જોઈએ',
      mr: 'मला हे हवे',
      bn: 'আমি এটা নেব',
      ta: 'இது எனக்கு வேண்டும்',
      te: 'ఇది నాకు కావాలి',
      kn: 'ಇದು ನನಗೆ ಬೇಕು',
      ml: 'എനിക്ക് ഇത് വേണം',
      pa: 'ਮੈਨੂੰ ਇਹ ਚਾਹੀਦਾ ਹੈ',
    },
  },
  {
    id: 's-discount',
    category: 'Shopping & Market',
    english: 'Can I get a discount?',
    translations: {
      en: 'Can I get a discount?',
      hi: 'क्या कुछ छूट मिलेगी?',
      gu: 'થોડી છૂટ મળશે?',
      mr: 'थोडी सूट मिळेल का?',
      bn: 'কিছু ছাড় পাব?',
      ta: 'சிறிது தள்ளுபடி கிடைக்குமா?',
      te: 'కొంచెం తగ్గింపు ఉంటుందా?',
      kn: 'ಸ್ವಲ್ಪ ರಿಯಾಯಿತಿ ಸಿಗುತ್ತದೆಯೇ?',
      ml: 'കുറച്ച് ആനുകൂല്യം കിട്ടുമോ?',
      pa: 'ਕੁਝ ਰਿਆਇਤ ਮਿਲੇਗੀ?',
    },
  },
  {
    id: 's-where-market',
    category: 'Shopping & Market',
 english: 'Where is the market?',
    translations: {
      en: 'Where is the market?',
      hi: 'बाज़ार कहाँ है?',
      gu: 'બજાર ક્યાં છે?',
      mr: 'बाजार कुठे आहे?',
      bn: 'বাজার কোথায়?',
      ta: 'சந்தை எங்கே உள்ளது?',
      te: 'మార్కెట్ ఎక్కడ ఉంది?',
      kn: 'ಮಾರುಕಟ್ಟೆ ಎಲ್ಲಿದೆ?',
      ml: 'വിപണി എവിടെയാണ്?',
      pa: 'ਬਾਜ਼ਾਰ ਕਿੱਥੇ ਹੈ?',
    },
  },

  // ── Transport ──
  {
    id: 't-how-to',
    category: 'Transport',
    english: 'How do I get to this place?',
    translations: {
      en: 'How do I get to this place?',
      hi: 'मुझे वहाँ कैसे जाना है?',
      gu: 'મને ત્યાં કેવી રીતે જવાય?',
      mr: 'मला तिथे कसे जायचे?',
      bn: 'আমি সেখানে কীভাবে যাব?',
      ta: 'அங்கே நான் எப்படி போவது?',
      te: 'అక్కడకు నేను ఎలా వెళ్ళాలి?',
      kn: 'ಅಲ್ಲಿಗೆ ನಾನು ಹೇಗೆ ಹೋಗಲಿ?',
      ml: 'അങ്ങോട്ട് ഞാൻ എങ്ങനെ പോകും?',
      pa: 'ਮੈਨੂੰ ਉੱਥੇ ਕਿਵੇਂ ਜਾਣਾ ਹੈ?',
    },
  },
  {
    id: 't-how-far',
    category: 'Transport',
    english: 'How far is it?',
    translations: {
      en: 'How far is it?',
      hi: 'वह कितनी दूर है?',
      gu: 'તે કેટલી દૂર છે?',
      mr: 'ते किती लांब आहे?',
      bn: 'কত দূর?',
      ta: 'எவ்வளவு தூரம் உள்ளது?',
      te: 'ఎంత దూరం ఉంది?',
      kn: 'ಎಷ್ಟು ದೂರ ಇದೆ?',
      ml: 'എത്ര അകലെയാണ്?',
      pa: 'ਕਿੰਨਾ ਦੂਰ ਹੈ?',
    },
  },
  {
    id: 't-take-me',
    category: 'Transport',
    english: 'Take me to this address',
    translations: {
      en: 'Take me to this address',
      hi: 'मुझे इस पते पर ले चलिए',
      gu: 'મને આ સરનામે લઈ જાઓ',
      mr: 'मला या पत्त्यावर न्या',
      bn: 'আমাকে এই ঠিকানায় নিয়ে যান',
      ta: 'என்னை இந்த முகவரிக்கு அழைத்துச் செல்லுங்கள்',
      te: 'నన్ను ఈ చిరునామాకి తీసుకెళ్ళండి',
      kn: 'ನನ್ನನ್ನು ಈ ವಿಳಾಸಕ್ಕೆ ಕರೆದುಕೊಂಡು ಹೋಗಿ',
      ml: 'എന്നെ ഈ വിലാസത്തിലേക്ക് കൊണ്ടുപോകൂ',
      pa: 'ਮੈਨੂੰ ਇਸ ਪਤੇ ਤੇ ਲੈ ਜਾਓ',
    },
  },
  {
    id: 't-what-time',
    category: 'Transport',
    english: 'What time does it leave?',
    translations: {
      en: 'What time does it leave?',
      hi: 'यह कब तक निकलेगा?',
      gu: 'આ ક્યારે નીકળશે?',
      mr: 'ते कधी निघेल?',
      bn: 'কখন ছাড়বে?',
      ta: 'எப்போது புறப்படும்?',
      te: 'ఎప్పుడు బయలుదేరుతుంది?',
      kn: 'ಯಾವಾಗ ಹೊರಟುಹೋಗುತ್ತದೆ?',
      ml: 'എപ്പോഴാണ് പുറപ്പെടുന്നത്?',
      pa: 'ਇਹ ਕਦੇ ਨਿਕਲੇਗਾ?',
    },
  },
  {
    id: 't-ride-cost',
    category: 'Transport',
    english: 'How much for the ride?',
    translations: {
      en: 'How much for the ride?',
      hi: 'किराया कितना है?',
      gu: 'ભાડું કેટલું છે?',
      mr: 'भाडा किती आहे?',
      bn: 'ভাড়া কত?',
      ta: 'வண்டிக் கூலி எவ்வளவு?',
      te: 'ప్రయాణ ఛార్జీ ఎంత?',
      kn: 'ಪ್ರಯಾಣ ಶುಲ್ಕ ಎಷ್ಟು?',
      ml: 'യാത്രാച്ചാർജ് എത്ര?',
      pa: 'ਕਿਰਾਇਆ ਕਿੰਨਾ ਹੈ?',
    },
  },

  // ── Hotel ──
  {
    id: 'h-reservation',
    category: 'Hotel',
    english: 'I have a reservation',
    translations: {
      en: 'I have a reservation',
      hi: 'मेरी बुकिंग है',
      gu: 'મારી બુકિંગ છે',
      mr: 'माझी बुकिंग आहे',
      bn: 'আমার বুকিং আছে',
      ta: 'எனக்கு முன்பதிவு உள்ளது',
      te: 'నాకు బుకింగ్ ఉంది',
      kn: 'ನನ್ನ ಬುಕಿಂಗ್ ಇದೆ',
      ml: 'എനിക്ക് ബുക്കിംഗ് ഉണ്ട്',
      pa: 'ਮੇਰੀ ਬੁਕਿੰਗ ਹੈ',
    },
  },
  {
    id: 'h-room',
    category: 'Hotel',
    english: 'Do you have a room available?',
    translations: {
      en: 'Do you have a room available?',
      hi: 'क्या एक कमरा खाली है?',
      gu: 'શું એક રૂમ ખાલી છે?',
      mr: 'तुमच्याकडे खोली आहे का?',
      bn: 'কি কক্ষ পাওয়া যাব?',
      ta: 'அறை கிடைக்கிறதா?',
      te: 'గది లభ్యమా?',
      kn: 'ಕೋಣೆ ಲಭ್ಯವಿದೆಯೇ?',
      ml: 'റൂം ലഭ്യമാണോ?',
      pa: 'ਕੀ ਕੋਈ ਕਮਰਾ ਖਾਲੀ ਹੈ?',
    },
  },
  {
    id: 'h-checkout',
    category: 'Hotel',
    english: 'What time is check-out?',
    translations: {
      en: 'What time is check-out?',
      hi: 'चेक-आउट कब है?',
      gu: 'ચેક-આઉટ ક્યારે છે?',
      mr: 'चेक-आउट कधी आहे?',
      bn: 'চেক-আউট কয়টায়?',
      ta: 'செக்-அவுட் எப்போது?',
      te: 'చెక్-అవుట్ ఎప్పుడు?',
      kn: 'ಚೆಕ್-ಔಟ್ ಯಾವಾಗ?',
      ml: 'ചെക്ക്-ഔട്ട് എപ്പോഴാണ്?',
      pa: 'ਚੈਕ-ਆਊਟ ਕਦੇ ਹੈ?',
    },
  },
  {
    id: 'h-breakfast',
    category: 'Hotel',
    english: 'Is breakfast included?',
    translations: {
      en: 'Is breakfast included?',
      hi: 'क्या नाश्ता शामिल है?',
      gu: 'નાસ્તો સમાવેશ થાય છે?',
      mr: 'नाश्ता समाविष्ट आहे का?',
      bn: 'নাস্তা কি অন্তর্ভুক্ত?',
      ta: 'காலை உணவு உள்ளதா?',
      te: 'ఉదయం భోజనం ఉందా?',
      kn: 'ಬೆಳಗಿನ ತಿಂಡಿ ಸೇರಿದೆಯೇ?',
      ml: 'പ്രാതൽ ഉൾപ്പെട്ടതാണോ?',
      pa: 'ਕੀ ਨਾਸ਼ਤਾ ਸ਼ਾਮਲ ਹੈ?',
    },
  },
  {
    id: 'h-need-taxi',
    category: 'Hotel',
    english: 'I need a taxi',
    translations: {
      en: 'I need a taxi',
      hi: 'मुझे टैक्सी चाहिए',
      gu: 'મને ટૅક્સી જોઈએ',
      mr: 'मला टॅक्सी पाहिजे',
      bn: 'আমার একটা ট্যাক্সি দরকার',
      ta: 'எனக்கு டாக்ஸி வேண்டும்',
      te: 'నాకు టాక్సీ కావాలి',
      kn: 'ನನಗೆ ಟ್ಯಾಕ್ಸಿ ಬೇಕು',
      ml: 'എനിക്ക് ടാക്സി വേണം',
      pa: 'ਮੈਨੂੰ ਟੈਕਸੀ ਚਾਹੀਦੀ ਹੈ',
    },
  },

  // ── Emergency ──
  {
    id: 'e-help',
    category: 'Emergency',
    english: 'I need help',
    translations: {
      en: 'I need help',
      hi: 'मुझे मदद चाहिए',
      gu: 'મને મદદ જોઈએ',
      mr: 'मला मदत पाहिजे',
      bn: 'আমার সাহায্য দরকার',
      ta: 'எனக்கு உதவி வேண்டும்',
      te: 'నాకు సహాయం కావాలి',
      kn: 'ನನಗೆ ಸಹಾಯ ಬೇಕು',
      ml: 'എനിക്ക് സഹായം വേണം',
      pa: 'ਮੈਨੂੰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ',
    },
  },
  {
    id: 'e-hospital',
    category: 'Emergency',
    english: 'Where is the hospital?',
    translations: {
      en: 'Where is the hospital?',
      hi: 'अस्पताल कहाँ है?',
      gu: 'હોસ્પિટલ ક્યાં છે?',
      mr: 'रुग्णालय कुठे आहे?',
      bn: 'হাসপাতাল কোথায়?',
      ta: 'மருத்துவமனை எங்கே?',
      te: 'ఆసుపత్రి ఎక్కడ ఉంది?',
      kn: 'ಆಸ್ಪತ್ರೆ ಎಲ್ಲಿದೆ?',
      ml: 'ആശുപത്രി എവിടെ?',
      pa: 'ਹਸਪਤਾਲ ਕਿੱਥੇ ਹੈ?',
    },
  },
  {
    id: 'e-police',
    category: 'Emergency',
    english: 'Call the police',
    translations: {
      en: 'Call the police',
      hi: 'पुलिस को बुलाइए',
      gu: 'પોલીસને બોલાવો',
      mr: 'पोलीसांना बोलवा',
      bn: 'পুলিশ ডাকুন',
      ta: 'காவல்துறையை அழையுங்கள்',
      te: 'పోలీసులను పిలవండి',
      kn: 'ಪೊಲೀಸರನ್ನು ಕರೆಯಿರಿ',
      ml: 'പോലീസിനെ വിളിക്കൂ',
      pa: 'ਪੁਲਿਸ ਨੂੰ ਬੁਲਾਓ',
    },
  },
  {
    id: 'e-sick',
    category: 'Emergency',
    english: 'I feel sick',
    translations: {
      en: 'I feel sick',
      hi: 'मुझे बीमार लग रहा है',
      gu: 'મને બીમાર લાગે છે',
      mr: 'मला आजार वाटत आहे',
      bn: 'আমার অসুস্থ লাগছে',
      ta: 'எனக்கு உடம்பு சுளுக்கென்கிறது',
      te: 'నాకు అనారోగ్యంగా ఉంది',
      kn: 'ನನಗೆ ಅನಾರೋಗ್ಯವಾಗಿದೆ',
      ml: 'എനിക്ക് അസുഖം തോന്നുന്നു',
      pa: 'ਮੈਨੂੰ ਬੀਮਾਰ ਲੱਗਦਾ ਹੈ',
    },
  },
  {
    id: 'e-pharmacy',
    category: 'Emergency',
    english: 'Where is the pharmacy?',
    translations: {
      en: 'Where is the pharmacy?',
      hi: 'दवाई की दुकान कहाँ है?',
      gu: 'દવાની દુકાન ક્યાં છે?',
      mr: 'औषधाचे दुकान कुठे आहे?',
      bn: 'ওষুধের দোকান কোথায়?',
      ta: 'மருந்து கடை எங்கே?',
      te: 'మందు దుకాణం ఎక్కడ ఉంది?',
      kn: 'ಔಷಧಿ ಅಂಗಡಿ ಎಲ್ಲಿದೆ?',
      ml: 'ഫാർമസി എവിടെ?',
      pa: 'ਦਵਾਈ ਦੀ ਦੁਕਾਨ ਕਿੱਥੇ ਹੈ?',
    },
  },

  // ── Directions ──
  {
    id: 'd-temple',
    category: 'Directions',
    english: 'Where is the temple?',
    translations: {
      en: 'Where is the temple?',
      hi: 'मंदिर कहाँ है?',
      gu: 'મંદિર ક્યાં છે?',
      mr: 'मंदिर कुठे आहे?',
      bn: 'মন্দির কোথায়?',
      ta: 'கோயில் எங்கே?',
      te: 'దేవాలయం ఎక్కడ ఉంది?',
      kn: 'ದೇವಾಲಯ ಎಲ್ಲಿದೆ?',
      ml: 'ക്ഷേത്രം എവിടെ?',
      pa: 'ਮੰਦਰ ਕਿੱਥੇ ਹੈ?',
    },
  },
  {
    id: 'd-fort',
    category: 'Directions',
    english: 'How do I get to the fort?',
    translations: {
      en: 'How do I get to the fort?',
      hi: 'किले पर कैसे जाएँ?',
      gu: 'કિલ્લા પર કેવી રીતે જવાય?',
      mr: 'किल्ल्यावर कसे जायचे?',
      bn: 'কেল্লায় কীভাবে যাব?',
      ta: 'கோட்டைக்கு எப்படி போவது?',
      te: 'కోటకు ఎలా వెళ్ళాలి?',
      kn: 'ಕೋಟೆಗೆ ಹೇಗೆ ಹೋಗಲಿ?',
      ml: 'കോട്ടയിലേക്ക് എങ്ങനെ പോകും?',
      pa: 'ਕਿਲੇ ਤੇ ਕਿਵੇਂ ਜਾਣਾ ਹੈ?',
    },
  },
  {
    id: 'd-left-right',
    category: 'Directions',
    english: 'Turn left / Turn right',
    translations: {
      en: 'Turn left / Turn right',
      hi: 'बाएँ मुड़ें / दाएँ मुड़ें',
      gu: 'ડાબે વળો / જમણે વળો',
      mr: 'डावीकडे वळा / उजवीकडे वळा',
      bn: 'বামে ঘেুন / ডানে ঘেুন',
      ta: 'இடது திரும்பு / வலது திரும்பு',
      te: 'ఎడమకు మళ్ళండి / కుడికి మళ్ళండి',
      kn: 'ಎಡಕ್ಕೆ ತಿರುಗಿ / ಬಲಕ್ಕೆ ತಿರುಗಿ',
      ml: 'ഇടത്തോട്ട് തിരിയുക / വലത്തോട്ട് തിരിയുക',
      pa: 'ਖੱਬੇ ਮੁੜੋ / ਸੱਜੇ ਮੁੜੋ',
    },
  },
  {
    id: 'd-straight',
    category: 'Directions',
    english: 'Go straight',
    translations: {
      en: 'Go straight',
      hi: 'सीधे चलें',
      gu: 'સીધા ચાલો',
      mr: 'थोडके पुढे जा',
      bn: 'সোজা যান',
      ta: 'நேராக போங்கள்',
      te: 'నేరుగా వెళ్ళండి',
      kn: 'ನೇರಾಗಿ ಹೋಗಿ',
      ml: 'നേരെ പോകുക',
      pa: 'ਸਿੱਧੇ ਚੱਲੋ',
    },
  },
  {
    id: 'd-far',
    category: 'Directions',
    english: 'Is it very far?',
    translations: {
      en: 'Is it very far?',
      hi: 'क्या यह बहुत दूर है?',
      gu: 'શું તે બહુ દૂર છે?',
      mr: 'ते खूप लांब आहे का?',
      bn: 'খুব দূর কি?',
      ta: 'இது மிக தொலைவில் உள்ளதா?',
      te: 'ఇది చాలా దూరమా?',
      kn: 'ಇದು ತುಂಬ ದೂರವಿದೆಯೇ?',
      ml: 'ഇത് വളരെ അകലെയാണോ?',
      pa: 'ਕੀ ਇਹ ਬਹੁਤ ਦੂਰ ਹੈ?',
    },
  },
  {
    id: 'd-map',
    category: 'Directions',
    english: 'Can you show me on the map?',
    translations: {
      en: 'Can you show me on the map?',
      hi: 'क्या आप नक्शे में दिखा सकते हैं?',
      gu: 'શું તમે નકશા પર બતાવી શકો?',
      mr: 'तुम्ही नकाशावर दाखवू शकता का?',
      bn: 'মানচিত্রে দেখাবেন?',
      ta: 'வரைபடத்தில் காட்ட முடியுமா?',
      te: 'మ్యాప్‌లో చూపించగలవా?',
      kn: 'ನಕ್ಷೆಯಲ್ಲಿ ತೋರಿಸಬಹುದೇ?',
      ml: 'ഭൂപടത്തിൽ കാണിക്കാമോ?',
      pa: 'ਕੀ ਤੁਸੀਂ ਨਕਸ਼ੇ ਤੇ ਵਿਖਾ ਸਕਦੇ ਹੋ?',
    },
  },
];

export function getPhrasesByCategory(category: string): TranslationPhrase[] {
  return PHRASES.filter((p) => p.category === category);
}

export function translate(phrase: TranslationPhrase, lang: LangCode): string {
  return phrase.translations[lang] || phrase.translations.en;
}
